dateModified: 1616016188
email:
  fromEmail: post@ponzo.nl
  fromName: Craft
  transportType: craft\mail\transportadapters\Sendmail
plugins:
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
system:
  edition: solo
  live: true
  name: Craft
  schemaVersion: 3.6.6
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
