enableVersioning: true
handle: about
name: about
propagationMethod: all
siteSettings:
  4c1ef523-139f-4301-b6b2-58ea6b2277bb: # Craft
    enabledByDefault: true
    hasUrls: true
    template: _singles/about
    uriFormat: about
type: single
